version: "3.8"
services:
  database:
    image: postgres:9.6
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=docker_db
      - POSTGRES_USER=rubel
      - POSTGRES_PASSWORD=S3cr3T
  app:
    image: spring-liquibase-demo:master
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        JAR_FILE: ./target/*.jar
        APP_PROP_LOC: src/main/resources/application.properties
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      WAIT_HOSTS: database:5433
volumes:
  pgdata: